name: ci

on:
  push:
    branches:
      - main
  pull_request:
    - opened
    - reopened

jobs:
  semantic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - name: Run tests
        run: make test
