name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
        with:
          # We need ${{github.event.pull_request.commits}} + 1 commits.
          fetch-depth: 0
          # Use a different token so subsequent workflows are executed.
          # See https://github.community/t/action-does-not-trigger-another-on-push-tag-action/17148
          token: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          # We need ${{github.event.pull_request.commits}} + 1 commits.
          fetch-depth: 0
          token: ${{ github.token }}

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Lint commit message(s)
        run: |
          yarn add @commitlint/cli
          yarn add @commitlint/config-conventional
          yarn run commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - name: Run tests
        run: make test
  release:
    if: github.event_name == 'push'
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # We need ${{github.event.pull_request.commits}} + 1 commits.
          fetch-depth: 0
          # Use a different token so subsequent workflows are executed.
          # See https://github.community/t/action-does-not-trigger-another-on-push-tag-action/17148
          token: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: temurin

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Release
        env:
          # Don't use the default GITHUB_TOKEN here. Other workflows will be skipped.
          # See https://github.com/semantic-release/github#github-authentication
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
        run: |
          yarn add semantic-release
          yarn add @semantic-release/exec
          yarn add @semantic-release/git
          yarn run semantic-release
