name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"
      - run: go version
      - id: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: build-and-push
        run: make docker-build docker-push
        env:
          IMG: ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
